### PR TITLE
added step support to slider and add more precision to the slider (us…

### PR DESCRIPTION
**Pull request by GeMoschen**
…e BigDecimal for internal calculations)

This PR will add the following functionalities to the Slider class:
- defineable min/max values per slider (default from 0 to 100)
- user defineable step sizes for a slider (default= off)
- precise values (fixing floating point precision failures)

Those functionalities are major for a Slider and helpful in many situations (i.e. selecting values in a range from -1/+1 with a step size of 0.1.

### CODE REVIEW

**Comment by GeMoschen** [comment]
Sure, no hurry :)

**Comment by ShchAlexander** [comment]
Another option - to use BigDecimal everywhere in slider-related classes.

**Comment by GeMoschen** [comment]
As stated, I have removed the precision-related changes. So the only change in this PR is now the addition of the step-size.

**Comment by ShchAlexander** [comment]
Hello @GeMoschen, sorry for so late response, was busy with magistracy and achieveing master degree.
BTW I sucessfully passed all steps  🎉

And about pull request - I created changes under [pull/103](https://github.com/SpinyOwl/legui/pull/103) based on your initial commit, so currently it is almost in the same state as this PR.

Also I finally managed with Travis CI and Sonarcloud, so I'm going to merge it and create artifact.

Best regards,
Alex :)

**Comment by ShchAlexander** [comment]
Hello @GeMoschen!
Artifact with step size published under `1.5.0-SNAPSHOT` 👌

**Comment by GeMoschen** [comment]
Hey, wonderful :)
Thanks for the merge!

**Pull request closed without merging**
